### PR TITLE
Sugar RPi OS v1

### PR DESCRIPTION
**Pull request by 44yu5h**
- 1.5GB
- RPi Lite OS + Sugar shell
- Activities: default ones + tower-of-hanoi, number-guessing, flappy, turtleart-activity, and rpi_control_center
- Temporary fix for the browse-activity issue (remove v207 that comes from apt, install v208, install dependencies)

### CODE REVIEW

**Comment by 44yu5h** [comment]
@chimosky here!

**Comment by chimosky** [comment]
Looks good, I'm curious though, why the deletion of so many files?

**Comment by 44yu5h** [comment]
@chimosky 
> I'm curious though, why the deletion of so many files?

They are the files of `stage3` to `stage5`, which are required to build a *full* version of RPi (full desktop environment, additional packages, and apps that we don't need)

We are building till `stage2` which makes the *lite* version of RPi which is more than sufficient for our use case. Then we edit the `stage3` to install Sugar. It cuts the OS size to half.

Thanks

**Comment by chimosky** [comment]
I know what they are, why delete them when you could just create `SKIP_IMAGE` files?

**Comment by chimosky** [comment]
Yeah, I know what they are. I was wondering why you deleted them when `SKIP_IMAGE` files would've been just fine.

**Comment by 44yu5h** [comment]
Right but they would've just been redundant files. We'll never need them and additionally might create confusion for future contributors so it was best to get rid of them.

**Comment by chimosky** [comment]
Thanks for this!

**Pull request merged**
